music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'


urlpatterns = [
    #/music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/music/84/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),


]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=120)
    albumTitle= models.CharField(max_length=120)
    genre = models.CharField(max_length=50)
    albumLogo=models.CharField(max_length=1000)

    def __str__(self):
        return self.albumTitle + ' - ' + self.artist

class Song(models.Model):
    album =  models.ForeignKey(Album,on_delete=models.CASCADE)
    fileType = models.CharField(max_length=10)
    songTitle = models.CharField(max_length=250)

    def __str__(self):
        return self.songTitle

music/views.py
from django.views import generic
from .models import Album



class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'


    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Viberr
        {% endblock %}
    </title>

    {% load staticfiles %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

        </button>
        <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
    </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li class="">
                    <a href=#>
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div id="form-group">
                    <input type="text" class="form-control" name="q" value="">

                </div>
                <button type="submit" class="btn btn-default">search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
</div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>

music/templates/music/details.html
{%  extends 'music/base.html' %}
{% block title %}
            Album Details
        {% endblock %}

{% block body %}
    <img src="{{ album.albumLogo }}">

    <h1>{{ album.albumTitle }}</h1>

    <h3>{{ album.artist }}</h3>

    {% if error_message %}
    <p><strong>{{ error_message }} </strong></p>
    {% endif %}


    <form action="{% url 'music:detail' album.id %}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
            <label for="song{{ forloop.counter }}">
            {{ song.songTitle}}
            {% if song.isFavorite %}
            <img src="images/1333b47590cc03e8290c73dd0ff8b2d3%20(1).jpg"
                 {% endif %}
            </label><br>
        {% endfor %}
            <input type="submit" value="Favorite">
    </form>

{% endblock %}

music/templates/music/index.html
<!-- Loads de path to your static file -->



{%  extends 'music/base.html' %}

{% block body %}

    <ul>

        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.albumTitle }}</a> </li>
        {% endfor %}
    </ul>


{% endblock  %}